name: flt_rest
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  firebase_auth: ^0.14.0
  shared_preferences: ^0.5.3+3
  rxdart: ^0.22.0
  flutter_swiper: ^1.1.6
  firebase_database: ^3.0.5
  get_it: ^1.0.3+2
  cloud_firestore: ^0.12.9
  fluro: ^1.5.1
  image_picker: ^0.6.1
  carousel_slider: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:

  uses-material-design: true
  assets:
      - assets/locale/locale_en.json
      - assets/locale/locale_vi.json
      - assets/images/tb.png
      - assets/images/menu1.png
      - assets/images/menu2.png
      - assets/images/menu3.png
      - assets/images/menu4.png
      - assets/images/menu5.png
      - assets/images/menu7.png
      - assets/images/menu8.png
      - assets/images/menu9.png
      - assets/images/menu10.png
      - assets/images/menu11.png
      - assets/images/menu12.png
      - assets/images/menu13.png
      - assets/images/menu14.png

